export const businessConfig = {
  name: "Selam CPA",
  legalName: "Selam Tax Inc.",
  dba: "Selam CPA",
  owner: "Yacob Tewelde, CPA, FCCA",
  phone: "301-640-8549",
  phoneE164: "+13016408549",
  email: "info@selamcpa.com",
  address: {
    street: "8593 Light Moon Way",
    city: "Laurel",
    state: "MD",
    zip: "20723",
    full: "8593 Light Moon Way, Laurel, MD 20723",
  },
  geography: {
    primary: "Laurel, MD",
    region: "DMV — DC, Maryland, Virginia",
    national: "All 50 states (virtual)",
    seoLocations: [
      "Laurel MD", "Columbia MD", "Baltimore MD",
      "Washington DC", "Northern Virginia",
      "Bethesda MD", "Silver Spring MD", "Rockville MD",
      "Arlington VA", "Alexandria VA",
    ],
  },
  calendly: "https://calendly.com/yber2001/30min",
  website: "https://selamcpa.com",
  social: {
    linkedin: "",
    facebook: "",
  },
  services: [
    "Tax Preparation & Planning",
    "Bookkeeping & Accounting",
    "Fractional CFO Services",
    "Audit, Review & Compilation",
    "AI Consulting for Accounting Firms",
    "Tax Strategy & Advisory",
  ],
  industries: [
    "Healthcare & Medical Practices",
    "Legal & Professional Services",
    "Real Estate & Property Management",
    "Technology & SaaS",
    "Retail & E-Commerce",
    "Construction & Contractors",
    "Nonprofits & Associations",
    "Restaurants & Hospitality",
  ],
};
