import { pgTable, text, serial, integer, boolean, timestamp, jsonb, varchar, decimal } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
});

export const contacts = pgTable("contacts", {
  id: serial("id").primaryKey(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone"),
  businessType: text("business_type"),
  message: text("message"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  status: text("status").default("new").notNull(), // new, contacted, converted
});

export const blogPosts = pgTable("blog_posts", {
  id: serial("id").primaryKey(),
  title: text("title").notNull(),
  slug: text("slug").notNull().unique(),
  excerpt: text("excerpt").notNull(),
  content: text("content").notNull(),
  category: text("category").notNull(),
  author: text("author").notNull(),
  publishedAt: timestamp("published_at").defaultNow().notNull(),
  status: text("status").default("published").notNull(), // draft, scheduled, published, archived
  contentType: text("content_type").default("monthly").notNull(), // weekly, monthly, quarterly, special
  scheduledFor: timestamp("scheduled_for"),
  autoGenerated: boolean("auto_generated").default(false),
  seoScore: integer("seo_score"),
  socialMediaPosted: boolean("social_media_posted").default(false),
});

export const contentSchedule = pgTable("content_schedule", {
  id: serial("id").primaryKey(),
  contentType: text("content_type").notNull(), // weekly, monthly, quarterly
  frequency: text("frequency").notNull(), // daily, weekly, monthly, quarterly
  nextRunDate: timestamp("next_run_date").notNull(),
  lastRunDate: timestamp("last_run_date"),
  isActive: boolean("is_active").default(true),
  topicCategories: text("topic_categories").array(), // Array of preferred topic categories
  publishTime: text("publish_time").default("09:00"), // HH:MM format
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const contentAnalytics = pgTable("content_analytics", {
  id: serial("id").primaryKey(),
  blogPostId: integer("blog_post_id").references(() => blogPosts.id),
  views: integer("views").default(0),
  uniqueViews: integer("unique_views").default(0),
  timeOnPage: integer("time_on_page").default(0), // seconds
  bounceRate: decimal("bounce_rate", { precision: 5, scale: 2 }),
  socialShares: integer("social_shares").default(0),
  emailClicks: integer("email_clicks").default(0),
  contactFormSubmissions: integer("contact_form_submissions").default(0),
  lastUpdated: timestamp("last_updated").defaultNow().notNull(),
});

export const emailNotifications = pgTable("email_notifications", {
  id: serial("id").primaryKey(),
  email: text("email").notNull(),
  notificationType: text("notification_type").notNull(), // new_post, weekly_digest, monthly_summary
  isActive: boolean("is_active").default(true),
  subscribedAt: timestamp("subscribed_at").defaultNow().notNull(),
  lastSentAt: timestamp("last_sent_at"),
});

export const contentBackups = pgTable("content_backups", {
  id: serial("id").primaryKey(),
  blogPostId: integer("blog_post_id").references(() => blogPosts.id),
  version: integer("version").notNull(),
  title: text("title").notNull(),
  slug: text("slug").notNull(),
  excerpt: text("excerpt").notNull(),
  content: text("content").notNull(),
  category: text("category").notNull(),
  author: text("author").notNull(),
  status: text("status").notNull(),
  contentType: text("content_type").notNull(),
  autoGenerated: boolean("auto_generated"),
  seoScore: integer("seo_score"),
  changeReason: text("change_reason"), // created, scheduled_update, manual_edit, ai_revision
  backupCreatedAt: timestamp("backup_created_at").defaultNow().notNull(),
  originalPublishedAt: timestamp("original_published_at").notNull(),
});

export const calculators = pgTable("calculators", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  description: text("description").notNull(),
  type: text("type").notNull(), // tax, roi, cash-flow, custom
  config: jsonb("config").notNull(), // calculator configuration
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const chatMessages = pgTable("chat_messages", {
  id: serial("id").primaryKey(),
  sessionId: text("session_id").notNull(),
  message: text("message").notNull(),
  response: text("response").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const userPurchases = pgTable("user_purchases", {
  id: serial("id").primaryKey(),
  email: varchar("email", { length: 255 }).notNull(),
  productType: varchar("product_type", { length: 50 }).notNull(), // 'digital_guidelines', 'consultation'
  productName: varchar("product_name", { length: 255 }).notNull(),
  amount: decimal("amount", { precision: 10, scale: 2 }).notNull(),
  stripePaymentIntentId: varchar("stripe_payment_intent_id", { length: 255 }),
  status: varchar("status", { length: 20 }).notNull().default("completed"), // 'pending', 'completed', 'refunded'
  purchaseDate: timestamp("purchase_date").defaultNow(),
  accessExpiresAt: timestamp("access_expires_at"), // for time-limited access
});

export const userProgress = pgTable("user_progress", {
  id: serial("id").primaryKey(),
  email: varchar("email", { length: 255 }).notNull(),
  guideTitle: varchar("guide_title", { length: 255 }).notNull(),
  sectionsCompleted: integer("sections_completed").default(0),
  totalSections: integer("total_sections").notNull(),
  lastAccessedAt: timestamp("last_accessed_at").defaultNow(),
  completedAt: timestamp("completed_at"),
  notes: text("notes"),
});

export const personalizedRecommendations = pgTable("personalized_recommendations", {
  id: serial("id").primaryKey(),
  email: varchar("email", { length: 255 }).notNull(),
  recommendationType: varchar("recommendation_type", { length: 50 }).notNull(), // 'guide', 'consultation', 'tool'
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description").notNull(),
  priority: integer("priority").default(1), // 1-5, higher is more important
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
  dismissedAt: timestamp("dismissed_at"),
});

export const careerApplications = pgTable("career_applications", {
  id: serial("id").primaryKey(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name").notNull(),
  email: text("email").notNull(),
  phone: text("phone").notNull(),
  position: text("position").notNull(),
  experience: text("experience").notNull(),
  coverLetter: text("cover_letter"),
  resumeUrl: text("resume_url"),
  linkedinUrl: text("linkedin_url"),
  portfolioUrl: text("portfolio_url"),
  status: text("status").default("new").notNull(),
  notes: text("notes"),
  submittedAt: timestamp("submitted_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export const seoData = pgTable("seo_data", {
  id: serial("id").primaryKey(),
  page: text("page").notNull().unique(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  keywords: text("keywords"),
  ogTitle: text("og_title"),
  ogDescription: text("og_description"),
  ogImage: text("og_image"),
  ogImageAlt: text("og_image_alt"),
  twitterTitle: text("twitter_title"),
  twitterDescription: text("twitter_description"),
  twitterImage: text("twitter_image"),
  canonicalUrl: text("canonical_url"),
  metaRobots: text("meta_robots").default("index, follow"),
  structuredData: text("structured_data"),
  lastUpdated: timestamp("last_updated").defaultNow().notNull(),
});

/**
 * Drafts for social-media posts that an AI generates and a human approves
 * before they go live. The flow:
 *   1. A draft is created with status="pending" and a single-use approvalToken.
 *   2. The token is emailed to the approver as one-click approve/reject links.
 *   3. On approve → publish via the platform API, transition to "posted"
 *      (or "failed" with errorMessage). On reject → transition to "rejected".
 *
 * The approvalToken column is unique so each token redeems exactly once.
 */
export const socialPostDrafts = pgTable("social_post_drafts", {
  id: serial("id").primaryKey(),
  platform: text("platform").notNull().default("facebook"), // facebook (room to grow: linkedin, twitter, ...)
  source: text("source").notNull(), // ai_blog, ai_topic, manual
  blogPostId: integer("blog_post_id").references(() => blogPosts.id),
  topic: text("topic"),
  message: text("message").notNull(),
  link: text("link"),
  status: text("status").notNull().default("pending"), // pending, approved, posted, rejected, failed
  approvalToken: text("approval_token").notNull().unique(),
  externalPostId: text("external_post_id"),
  errorMessage: text("error_message"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  decidedAt: timestamp("decided_at"),
  postedAt: timestamp("posted_at"),
});

export const insertSocialPostDraftSchema = createInsertSchema(socialPostDrafts).omit({
  id: true,
  createdAt: true,
  decidedAt: true,
  postedAt: true,
  externalPostId: true,
  errorMessage: true,
});

export const insertContactSchema = createInsertSchema(contacts).omit({
  id: true,
  createdAt: true,
  status: true,
});

export const insertBlogPostSchema = createInsertSchema(blogPosts).omit({
  id: true,
  publishedAt: true,
  status: true,
});

export const insertCalculatorSchema = createInsertSchema(calculators).omit({
  id: true,
  createdAt: true,
});

export const insertChatMessageSchema = createInsertSchema(chatMessages).omit({
  id: true,
  createdAt: true,
});

export const insertUserPurchaseSchema = createInsertSchema(userPurchases).omit({
  id: true,
  purchaseDate: true,
});

export const insertUserProgressSchema = createInsertSchema(userProgress).omit({
  id: true,
  lastAccessedAt: true,
});

export const insertPersonalizedRecommendationSchema = createInsertSchema(personalizedRecommendations).omit({
  id: true,
  createdAt: true,
});

export const insertCareerApplicationSchema = createInsertSchema(careerApplications).omit({
  id: true,
  submittedAt: true,
  updatedAt: true,
});

export const insertSeoDataSchema = createInsertSchema(seoData).omit({
  id: true,
  lastUpdated: true,
});

export const insertContentScheduleSchema = createInsertSchema(contentSchedule).omit({
  id: true,
  createdAt: true,
});

export const insertContentAnalyticsSchema = createInsertSchema(contentAnalytics).omit({
  id: true,
  lastUpdated: true,
});

export const insertEmailNotificationSchema = createInsertSchema(emailNotifications).omit({
  id: true,
  subscribedAt: true,
});

export const insertContentBackupSchema = createInsertSchema(contentBackups).omit({
  id: true,
  backupCreatedAt: true,
});

export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;
export type InsertContact = z.infer<typeof insertContactSchema>;
export type Contact = typeof contacts.$inferSelect;
export type InsertBlogPost = z.infer<typeof insertBlogPostSchema>;
export type BlogPost = typeof blogPosts.$inferSelect;
export type InsertCalculator = z.infer<typeof insertCalculatorSchema>;
export type Calculator = typeof calculators.$inferSelect;
export type InsertChatMessage = z.infer<typeof insertChatMessageSchema>;
export type ChatMessage = typeof chatMessages.$inferSelect;
export type InsertUserPurchase = z.infer<typeof insertUserPurchaseSchema>;
export type UserPurchase = typeof userPurchases.$inferSelect;
export type InsertUserProgress = z.infer<typeof insertUserProgressSchema>;
export type UserProgress = typeof userProgress.$inferSelect;
export type InsertPersonalizedRecommendation = z.infer<typeof insertPersonalizedRecommendationSchema>;
export type PersonalizedRecommendation = typeof personalizedRecommendations.$inferSelect;
export type InsertCareerApplication = z.infer<typeof insertCareerApplicationSchema>;
export type CareerApplication = typeof careerApplications.$inferSelect;
export type InsertSeoData = z.infer<typeof insertSeoDataSchema>;
export type SeoData = typeof seoData.$inferSelect;
export type InsertContentSchedule = z.infer<typeof insertContentScheduleSchema>;
export type ContentSchedule = typeof contentSchedule.$inferSelect;
export type InsertContentAnalytics = z.infer<typeof insertContentAnalyticsSchema>;
export type ContentAnalytics = typeof contentAnalytics.$inferSelect;
export type InsertEmailNotification = z.infer<typeof insertEmailNotificationSchema>;
export type EmailNotification = typeof emailNotifications.$inferSelect;
export type InsertContentBackup = z.infer<typeof insertContentBackupSchema>;
export type ContentBackup = typeof contentBackups.$inferSelect;
export type InsertSocialPostDraft = z.infer<typeof insertSocialPostDraftSchema>;
export type SocialPostDraft = typeof socialPostDrafts.$inferSelect;

/**
 * Tracks Stripe Checkout session IDs that have already been used to claim
 * agent lifetime access. Enforces single-use redemption via a UNIQUE
 * constraint on session_id so that concurrent or replayed redemption
 * attempts fail atomically at the database level.
 */
export const agentSessionRedemptions = pgTable("agent_session_redemptions", {
  id: serial("id").primaryKey(),
  sessionId: text("session_id").notNull().unique(),
  stripeCustomerId: text("stripe_customer_id").notNull(),
  redeemedAt: timestamp("redeemed_at").defaultNow().notNull(),
});

export type AgentSessionRedemption = typeof agentSessionRedemptions.$inferSelect;

export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
});
